apiVersion: v2
name: ultimate-saas-platform
description: A comprehensive Helm chart for the Ultimate AI-Native SaaS Platform
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/thomas-carter-aic/ultimate-saas-base
sources:
  - https://github.com/thomas-carter-aic/ultimate-saas-base
maintainers:
  - name: Platform Team
    email: platform-team@ultimate-saas.com
keywords:
  - saas
  - ai
  - machine-learning
  - multi-tenant
  - microservices
  - kubernetes
annotations:
  category: Application
dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: kafka
    version: 22.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
  - name: prometheus
    version: 23.x.x
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: 6.x.x
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.grafana.enabled
